name: CI for Flask Project

# Trigger workflow on push to the 'main' branch or pull requests targeting 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test: # Name of the job
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 # Specify the version of Python

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run unit tests
    - name: Run Tests
      run: |
        pytest

